Repository dev-backpack/cllm, pull requests merged in 2024-03, with the labels that each got.

#37 Add badges and connect with us and license section
  README.md
Labels: enhancement

#34 Add error handling for CLI errors
  src/main.rs
Labels: bug

#36 Add command to store and display previous search history in the database
  Cargo.toml
  src/commands/history/mod.rs
  src/commands/mod.rs
  src/commands/search/mod.rs
Labels: enhancement

#38 Add CLLM ASCII art logo to main.rs
  src/main.rs
Labels: enhancement

#39 Create project homepage and documentation using docusaurus
  cllm-website/.gitignore
  cllm-website/README.md
  cllm-website/babel.config.js
  cllm-website/blog/2024-03-15-welcome/cllm-example-1.gif
  cllm-website/blog/2024-03-15-welcome/index.md
  cllm-website/blog/authors.yml
  cllm-website/community/0-support.md
  cllm-website/community/1-team.mdx
  cllm-website/community/2-contributing.md
  cllm-website/docs/cllm-example-1.gif
  cllm-website/docs/commands/_category_.json
  cllm-website/docs/commands/describe.md
  cllm-website/docs/commands/history.md
  cllm-website/docs/commands/search.md
  cllm-website/docs/commands/set/index.mdx
  cllm-website/docs/commands/set/key.md
  cllm-website/docs/getting-started.md
  cllm-website/docs/intro.md
  cllm-website/docusaurus.config.ts
  cllm-website/package-lock.json
  cllm-website/package.json
  cllm-website/sidebars.ts
  cllm-website/sidebarsCommunity.js
  cllm-website/src/components/HomepageFeatures/index.tsx
  cllm-website/src/components/HomepageFeatures/styles.module.css
  cllm-website/src/components/TeamProfileCards/index.tsx
  cllm-website/src/css/custom.css
  cllm-website/src/pages/index.module.css
  cllm-website/src/pages/index.tsx
  cllm-website/src/pages/markdown-page.md
  cllm-website/static/.nojekyll
  cllm-website/static/img/cllm-example-1.gif
  cllm-website/static/img/docusaurus-social-card.jpg
  cllm-website/static/img/docusaurus.png
  cllm-website/static/img/favicon.ico
  cllm-website/static/img/logo.svg
  cllm-website/static/img/undraw_docusaurus_mountain.svg
  cllm-website/static/img/undraw_docusaurus_react.svg
  cllm-website/static/img/undraw_docusaurus_tree.svg
  cllm-website/tsconfig.json
Labels: documentation, enhancement

#41 Add Continous Deployment for document using GitHub Pages
  .github/workflows/deploy.yml
Labels: enhancement

#42 Fix GitHub Page Deployment Error
  .github/workflows/deploy.yml
Labels: bug

#43 Add `describe` command to provide descriptions of commands and their options
  src/commands/describe/mod.rs
  src/commands/mod.rs
Labels: enhancement

#44 Grant 'write' permission to upload-rust-binary-action upon Release registration
  .github/workflows/release.yml
Labels: bug
